---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: satellite
  name: satellite
spec: {}
---
apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: "satellite"
    name: "satellite"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "satellite:latest"
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/atgreen/tiysoo.git
      contextDir:
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
        env:
          - name: RHSM_USERNAME
            value: XXXXXXXXX
          - name: RHSM_PASSWORD
            value: XXXXXXXXXXX
          - name: RHSM_POOL
            value: XXXXXXXXXXXXXXXXXXXXX
          - name: FOREMAN_PASSWORD
            value: XXXXXXXX
        from:
          kind: DockerImage
          name: rhel7
        forcePull: true
      type: Docker
kind: List
metadata: {}
